engines:
  duplication:
    enabled: true
    exclude_fingerprints:
        - 7c2ed57eda9ffc6d49e3ed8994b6a561 #not duplicate code
    config:
      languages:
      - javascript
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: false
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- tests/
